---

github_directory: github.com/samuelclay/newsblur
git_web_repo: ssh://git@{{ github_directory }}
git_secrets_repo: ssh://git@github.com/samuelclay/newsblur-secrets

create_user: nb
local_key: "{{ lookup('file', lookup('env','HOME') + '/.ssh/id_rsa.pub') }}"
copy_local_key: "{{ lookup('file', '/srv/secrets-newsblur/keys/docker.key.pub') }}"
mongodb_keyfile: "{{ lookup('file', '/srv/secrets-newsblur/keys/mongodb_keyfile.key') }}"
mongodb_username: "{{ lookup('ini', 'mongodb_username section=admin file=/srv/secrets-newsblur/configs/mongodb_auth.ini') }}"
mongodb_password: "{{ lookup('ini', 'mongodb_password section=admin file=/srv/secrets-newsblur/configs/mongodb_auth.ini') }}"
sys_packages: [ 
  'git', 
  'python3', 
  'python3-dev', 
  'zsh', 
  'openssl', 
  'libssl-dev', 
  'libssl-doc', 
  'build-essential', 
  'ntp', 
  'htop'
]
grafana_password: "{{ lookup('ini', 'grafana_password section=grafana file=/srv/secrets-newsblur/configs/grafana.ini') }}"
