version: '2'
services:
  
  prometheus:
    container_name: prometheus
    image: prom/prometheus
    ports:
      - 9090:9090
    command: '--config.file=/etc/prometheus/prometheus.yml'
    volumes:
      - ./docker/prometheus/prometheus.docker.yml:/etc/prometheus/prometheus.yml
      - ./docker/prometheus/prometheus_rules.yml:/etc/prometheus/prometheus_rules.yml
      - ./docker/volumes/prometheus_data:/prometheus
    depends_on:
      - node-exporter
      - haproxy
    external_links:
      - haproxy

  node-exporter:
    container_name: node-exporter
    image: prom/node-exporter
    ports:
      - 9100:9100

  grafana:
    container_name: grafana
    image: grafana/grafana
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=pass
    depends_on:
      - prometheus
    ports:
      - 3000:3000
    volumes:
      - ./docker/volumes/grafana_data:/var/lib/grafana
      - ./docker/grafana/datasources:/etc/grafana/provisioning/datasources/
      - ./docker/grafana/dashboards/:/etc/grafana/provisioning/dashboards/
    external_links:
      - prometheus
