---
- name: Template grafana config
  template:
    src: /srv/newsblur/docker/grafana/grafana.ini.j2
    dest: /srv/newsblur/docker/grafana/grafana.ini

- name: Start grafana container
  become: yes
  docker_container:
    name: grafana
    image: grafana/grafana
    user: root
    env:
      GF_SECURITY_ADMIN_PASSWORD: "{{ grafana_password }}"
    ports:
      - "3000:3000"
    volumes:
      - /srv/newsblur/docker/grafana/grafana.ini:/etc/grafana/grafana.ini
      - /srv/newsblur/docker/volumes/grafana_data:/var/lib/grafana
      - /srv/newsblur/docker/grafana/datasources:/etc/grafana/provisioning/datasources/
      - /srv/newsblur/docker/grafana/dashboards/:/etc/grafana/provisioning/dashboards/
