---
- name: Start grafana container
  become: yes
  docker_container:
    name: grafana
    image: grafana/grafana
    environment:
      - GF_SECURITY_ADMIN_PASSWORD="{{ grafana_password }}"
    ports:
      - "3000:3000"
    volumes:
      - /srv/newsblur/docker/volumes/grafana_data:/var/lib/grafana
