---
- name: DEPLOY -> task
  hosts: task
  gather_facts: false
  vars_files:
    - ../env_vars/base.yml

  tasks:
    - name: Pull newsblur_web github
      git:
        repo: https://github.com/samuelclay/NewsBlur.git
        dest: /srv/newsblur/
        version: dashboard3
      register: pulled
    
    - block:
        - name: Reload celery
          become: yes
          command: "docker kill --signal=HUP {{ item.service_name }}"
          when: item.service_name in inventory_hostname
          with_items:
            - service_name: task-celery
            - service_name: task-work
      rescue:
        - name: Restart celery
          become: yes
          command: "docker start task-work"

    - name: Stop celery
      become: yes
      docker_container:
        state: stopped
        name: "{{ item.service_name }}"
        container_default_behavior: no_defaults
      when: item.service_name in inventory_hostname
      with_items:
        - service_name: task-celery
        - service_name: task-work
      tags:
        - never
        - stop

    - name: Start celery
      become: yes
      docker_container:
        state: started
        name: "{{ item.service_name }}"
        container_default_behavior: no_defaults
      when: item.service_name in inventory_hostname
      with_items:
        - service_name: task-celery
        - service_name: task-work
      tags:
        - never
        - start
