---
- name: DEPLOY -> monitor
  hosts: db
  gather_facts: false
  vars_files:
    - ../env_vars/base.yml

  tasks:
    - name: Pull newsblur_web github
      git:
        repo: https://github.com/samuelclay/NewsBlur.git
        dest: /srv/newsblur/
        version: dashboard3
      register: pulled
    
    - name: Reload monitor
      become: yes
      command: "docker restart monitor"
