---
- name: DEPLOY -> staging
  hosts: staging
  gather_facts: false
  vars_files:
    - ../env_vars/base.yml

  tasks:
    - name: Pull newsblur_web github
      git:
        repo: https://github.com/samuelclay/NewsBlur.git
        dest: /srv/newsblur/
        version: master
      register: pulled
    
    - name: Reload gunicorn
      become: yes
      command: "docker kill --signal=HUP newsblur_web"
      # when: pulled.changed
