---
- name: SETUP -> task containers
  hosts: task
  vars_files:
    - ../env_vars/base.yml
  vars:
    - update_apt_cache: yes
    - motd_role: task
  roles:
    - {role: 'base', tags: 'base'}
    - {role: 'ufw', tags: 'ufw'}
    - {role: 'docker', tags: 'docker'}
    - {role: 'repo', tags: 'repo'}
    - {role: 'dnsmasq', tags: 'dnsmasq'}
    - {role: 'consul', tags: 'consul'}
    - {role: 'consul-client', tags: 'consul'}
    - {role: 'apns', tags: 'apns'}
    # - {role: 'netdata', tags: 'netdata'}
    - {role: 'node-exporter', tags: 'node-exporter'}
    - {role: 'celery_task', tags: 'celery'}
