---
- name: SETUP -> mongo containers
  hosts: mongo
  vars:
    - update_apt_cache: yes
    - motd_role: db
  vars_files:
    - ../env_vars/base.yml
  
  roles:
    - {role: 'base', tags: 'base'}
    - {role: 'ufw', tags: 'ufw'}
    - {role: 'docker', tags: 'docker'}
    - {role: 'repo', tags: 'repo'}
    - {role: 'dnsmasq', tags: 'dnsmasq'}
    - {role: 'consul', tags: 'consul'}
    - {role: 'consul-client', tags: 'consul'}
    - {role: 'node-exporter', tags: ['node-exporter', 'metrics']}
    - {role: 'mongo', tags: 'mongo'}
    - {role: 'monitor', tags: 'monitor'}
    - {role: 'benchmark', tags: 'benchmark'}
