---
- name: Permissions for mongo
  become: yes
  file:
    state: directory
    mode: 0777
    path: /var/log/mongodb

- name: Start db-mongo docker container
  become: yes
  docker_container:
    name: mongo
    image: mongo:3.6
    state: started
    container_default_behavior: no_defaults
    restart_policy: unless-stopped
    network_mode: host
    command: --config /etc/mongod.conf
    volumes:
      - /mnt/{{ inventory_hostname | regex_replace('db-|-', '') }}:/data/db
      - /srv/newsblur/ansible/roles/mongo/templates/mongo.conf:/etc/mongod.conf
      - /var/log/mongodb/:/var/log/mongodb/

- name: Register mongo in consul
  tags: consul
  become: yes
  template:
    src: consul_service.json
    dest: /etc/consul.d/mongo.json
  when: (inventory_hostname | regex_replace('[0-9]+', '')) in ['db-mongo', 'db-mongo-secondary'] or inventory_hostname.startswith('db2')
  notify:
    - reload consul

- name: Register mongo-analytics in consul
  tags: consul
  become: yes
  template:
    src: consul_service.analytics.json
    dest: /etc/consul.d/mongo.json
  when: (inventory_hostname | regex_replace('[0-9]+', '')) == 'db-mongo-analytics' or inventory_hostname.startswith('db3')
  notify:
    - reload consul
